name:                random-access-file
version:             0.1.0.0
github:              "portnov/random-access-file"
license:             BSD3
author:              "Ilya V. Portnov"
maintainer:          "portnov84@rambler.ru"
copyright:           "2018 Ilya Portnov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Random file access methods, supporting application-level page cache.
category:            System

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/portnov/random-access-file#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- stm
- unix
- unix-bytestring
- unix-memory
- concurrent-extra
- lrucaching

library:
  source-dirs:         src
  ghc-options:
  - -fwarn-unused-imports

benchmarks:
  random-access-file-benchmark:
    dependencies:
      - criterion
      - random
      - random-access-file
    source-dirs: benchmark
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-unused-imports

