name:                random-access-file
version:             0.1.0.0
github:              "portnov/iotests"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/iotests#readme>

dependencies:
- base >= 4.7 && < 5
- random
- bytestring
- containers
- stm
- unix
- unix-bytestring
- unix-memory
- concurrent-extra
- lrucaching

library:
  source-dirs:         src
  ghc-options:
  - -fwarn-unused-imports

benchmarks:
  random-access-file-benchmark:
    dependencies:
      - criterion
      - random-access-file
    source-dirs: benchmark
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-unused-imports

